### PR TITLE
Extract local storage management to hook

### PR DESCRIPTION
**Pull request by chriswilty**
## Description

App.tsx is really large, as it handles
- local storage read / update and storing in component state
- logic for opening / closing most of the dialogs
- passing these into MainComponent

I've extracted the local storage handling into a hook.

## Checklist

Have you done the following?

- [x] Linked the relevant Issue (done originally as part of prep for authentication in UI: #807)
- [x] Added tests
- [x] Ensured the workflow steps are passing

### CODE REVIEW

**Review by pmarsh-scottlogic — APPROVED** [review]
seems to work well. Nice to make App.tsx smaller!

**Comment by chriswilty** [comment]
@pmarsh-scottlogic Yeah, next step would be to extract all that dialog stuff, though right now I'm struggling to see a nice way of achieving that...

**Comment by chriswilty** [comment]
Just realised I've been lazy and not added any unit tests for the hook... I'll do that shortly.

**Comment by pmarsh-scottlogic** [comment]
exemplary work on the tests

**Pull request merged**
