### PR TITLE
adding formatting for 200% magnification on standard screen

### PR DESCRIPTION
**Pull request by AAloshine-scottlogic**
## Description
added media break querys to decrease padding and margins so that the app fully displays all functions at 200% magnification. 

## Screenshots

image

ticket link:
https://github.com/ScottLogic/prompt-injection/issues/699

### CODE REVIEW

**Review by dhinrichs-scottlogic — CHANGES_REQUESTED** [review]
Here's what I found so far:
- On Chrome, when you magnify to 150% the Getting Started and Reset Progress buttons touch
- Could you move the Level 1 2 3 section further to the left so that the Reset Progress doesn't wrap?

**Review by chriswilty — CHANGES_REQUESTED** [review]
This isn't working as you intended, since switching to rems, so I assume you didn't run it locally to check

The logic is basically inverted now at normal (100%) zoom, as in, the "render everything smaller and tighter" breakpoint kicks in _from_ 600px width and upwards:

At 599px:
image

At 600px:
image

At 1480px (laptop screen):
image

And at 200% zoom on full laptop screen it still doesn't all fit:
image

If I rewind to your original code using 150DPI, it doesn't work well on my screen where I have my taskbar vertically:

image

And of course with DPI we don't get any allowance for (available) screen width nor basefont increases.

I think you'd be wise to start from scratch, and work out a breakpoint (in rem) where things become too tight, on a standard ScottLogic laptop (1920x1200). If need be, you can gracefully respond using a couple of breakpoints, though that might be beyond the scope of this ticket if you can get everything working nicely with a single change. Remember to test it with
- zooming in/out, up to 200%
- changing base font at 100% zoom only, up to 32px
- Resizing the window

**Comment by AAloshine-scottlogic** [comment]
Ah crumbs, youre right! i've been using the desktop to test the magnification but havent used my laptop since i usually have my code on the laptop screen and the website open on the desktop one. I'll go ahead and try and figure out the correct rem for the laptop screen then

**Comment by chriswilty** [comment]
This is looking really good now 💎 

Just the minor suggestions I chucked your way on teams, then very happy to approve ✅

**Review by chriswilty — APPROVED** [review]
Lovely!

**Pull request merged**
