### PR TITLE
685 fixed blank error message showing

### PR DESCRIPTION
**Pull request by gsproston-scottlogic**
## Description

Fixed the instances of blank error messages by making sure the `CHAT_MESSAGE_TYPE` enum was synced on the frontend and backend.

## Notes

- The blank error message was the result of the frontend trying to display the system role as a message.

## Checklist

Have you done the following?

- [x] Linked the relevant Issue
- [x] Added tests
- [x] Ensured the workflow steps are passing

### CODE REVIEW

**Comment by pmarsh-scottlogic** [comment]
Whoops, I'd taken these out because I couldn't find anywhere that they were used. was I mistaken?

**Review by heatherlogan-scottlogic — APPROVED** [review]
⭐

**Review by pmarsh-scottlogic — CHANGES_REQUESTED** [review]
mind adding a comment to make it clear that these two are needed for syncing so another developer like me doesn't remove them with good intentions

**Comment by gsproston-scottlogic** [comment]
> mind adding a comment to make it clear that these two are needed for syncing so another developer like me doesn't remove them with good intentions

Yep can do, I've kept it general in case more values are added on the backend which aren't used on the frontend.

**Review by pmarsh-scottlogic — APPROVED** [review]
🦄

**Pull request merged**
